version: '3'

services:
  db:
    image: postgres
    ports:
      - 5434:5432
    container_name: mediumclone
    restart: always
    tty: true
    volumes:
      - ./.docker/dbdata:/var/lib/postgresql/data
      - ./.docker/postgres:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=mediumclone
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123